# name: Python CI with cache pip

# on:
#   push:
#     branches: [ "main", "ci-pytest"]
#   pull_request:
#     branches: [ "main","ci-pytest"]
#   workflow_dispatch:  # Allows manual trigger from CLI or UI

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: 
#         label: [activation]

#     steps:
#       # Step 1: Checkout code
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Step 2: Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
       
#       # Step 3: Cache pip dependencies   
#       - name: Get pip cache directory
#         id: pip-cache
#         run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

#       - name: Cache pip dependencies
#         uses: actions/cache@v3
#         with:
#           path: ${{ steps.pip-cache.outputs.dir }}
#           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       # Step 4: Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 5: Run pytest
#       - name: Run tests with pytest
#         run: |
#           export PYTHONPATH=.
#           pytest -m ${{ matrix.label }}

name: Separate model testing

on:
  push:
    branches: [ "main", "compound_model"]
  pull_request:
    branches: [ "main", "compound_model"]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['addmul_model']

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
    
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Pytest
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
        
      - name: Check file changes
        run: |
          echo "BRANCH NAME: $GITHUB_REF_NAME"          
             
          my_list=("addcmul_model" "addcdiv_model" "compound_model")
          git fetch origin main #--depth=2
          for item in "${my_list[@]}"; do
            if [[ "$GITHUB_REF_NAME" != "main" ]]; then
              if git diff --name-only origin/main HEAD | grep "$item";then
                if [ -z "$new_list" ]; then
                  new_list="$item"
                else
                  new_list="$new_list,$item"              
                fi
                echo "Workflows file modified: $item"
              fi
            else
              if git diff --name-only main@{1} main@{0} | grep "$item"; then
                if [ -z "$new_list" ]; then
                  new_list="$item"
                else
                  new_list="$new_list,$item"              
                fi
                echo "Workflows file modified: $item"
              fi              
            fi
          done

          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH: $(pwd)"
          # Convert string to array
          IFS=',' read -r -a arr <<< "$new_list"
          
          for item in "${arr[@]}"; do
            #[ -n "$item" ] && echo "Running pytest on modified workflows" && pytest $item/tests -v
            extracted_name="${item%_model}"  #  If item is "addcdiv_model" , output will be just addcdiv
            test_files=$(grep -Rl "$extracted_name" */tests) # If extracted_name is just "compound", then it will run testcases wherever "compound" keyword is present
            PYTHONDONTWRITEBYTECODE=1 pytest -p no:cacheprovider $test_files
          done