# name: Python CI with cache pip

# on:
#   push:
#     branches: [ "main", "ci-pytest"]
#   pull_request:
#     branches: [ "main","ci-pytest"]
#   workflow_dispatch:  # Allows manual trigger from CLI or UI

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: 
#         label: [activation]

#     steps:
#       # Step 1: Checkout code
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Step 2: Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
       
#       # Step 3: Cache pip dependencies   
#       - name: Get pip cache directory
#         id: pip-cache
#         run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

#       - name: Cache pip dependencies
#         uses: actions/cache@v3
#         with:
#           path: ${{ steps.pip-cache.outputs.dir }}
#           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       # Step 4: Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 5: Run pytest
#       - name: Run tests with pytest
#         run: |
#           export PYTHONPATH=.
#           pytest -m ${{ matrix.label }}

name: Separate model testing

on:
  push:
    branches: [ "specfic-model-test"]
  pull_request:
    branches: [ "specfic-model-test"]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['addmul_model']

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
    
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Pytest
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
        
      - name: Check file changes
        run: |
          my_list=("addmul_model" "adddiv_model" "compound_model")
          git fetch origin main #--depth=2
          for item in "${my_list[@]}"; do
            if git diff --name-only origin/main HEAD | grep "$item";then
              if [ -z "$new_list" ]; then
                new_list="$item"
              else
                new_list="$new_list,$item"              
              fi
              echo "Workflows file modified: $item"
            fi
          done

          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH: $(pwd)"
          # Convert string to array
          IFS=',' read -r -a arr <<< "$new_list"
          
          for item in "${arr[@]}"; do
            [ -n "$item" ] && echo "Running pytest on modified workflows" && pytest $item/tests -v
            
            # Search for dependency folder changes as well
            # 1. Search for test files under tests/ that import specific model

            test_files=$(grep -Rl "import $item" */tests/)

            if [ -z "$test_files" ]; then
              echo "No test files imported"
            else
              # 3. Print the collected test files
              echo "Test files that import addcmul_model:"
              echo "$test_files"
              # 4. Run pytest only on the collected files
              pytest $test_files
            fi
          done